name = "telegram-content-bot"
main = "src/index.js"
compatibility_date = "2024-01-01"

[vars]
BOT_TOKEN = "YOUR_BOT_TOKEN"
ADMIN_USER_IDS = "123456789,987654321"
CHANNEL_ID = "@your_channel_id"

[[kv_namespaces]]
binding = "TELEGRAM_BOT_DATA"
id = "your_kv_namespace_id"
preview_id = "your_preview_kv_namespace_id"
