name: Run Tests

on:
  push:
    branches:
      - telegram
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: cd src && npm install
      - name: Run tests
        run: cd src && npx vitest run
